# ============================================================
# .gitlab-ci.yml — P&ID Component Library
# Publishes scoped npm package to GitLab Package Registry
# via semantic-release on master branch only.
# ============================================================

stages:
  - install
  - quality
  - build
  - release

# ── Global defaults ──────────────────────────────────────────
default:
  image: node:20-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull

# ── Variables ────────────────────────────────────────────────
variables:
  GIT_DEPTH: 0   # Full clone — semantic-release needs full history
  NPM_CONFIG_REGISTRY: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"

# ============================================================
# Stage: install
# ============================================================
install:
  stage: install
  script:
    - npm ci --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push

# ============================================================
# Stage: quality
# ============================================================
lint:
  stage: quality
  needs: [install]
  script:
    - npm run lint

test:
  stage: quality
  needs: [install]
  script:
    - npm run test -- --run
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 7 days

# ============================================================
# Stage: build
# ============================================================
build:
  stage: build
  needs: [install]
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

# ============================================================
# Stage: release  (master only)
# ============================================================
release:
  stage: release
  needs: [lint, test, build]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - when: never
  before_script:
    # semantic-release needs git
    - apk add --no-cache git
    # Generate .npmrc for publishing with CI_JOB_TOKEN
    - |
      echo "@my-group:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
      echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    # Git config for semantic-release tag/commit push
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git remote set-url origin "https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  script:
    - npx semantic-release
